# ##YAML Template

# #CUCUMBER SETUP
default: -p mobile -p device -p version -p perfil -p json --format progress
html: --format html --out=log/report_result.html
json: --format json --out=log/report_result.json

#AMBIENT VARIABLES
mobile: PLATFORM=android
perfil: CAPS=default
device: DEVICE=Moto_G7_Plus
version: VERSION=10